version: "2"
linters:
  enable:
    - depguard
    - errorlint
    - forbidigo
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: gopkg.in/yaml.v2
              desc: please use gopkg.in/yaml.v3 instead
            - pkg: github.com/pkg/errors
              desc: please use errors from the standard library instead
            - pkg: golang.org/x/xerrors
              desc: please use errors from the standard library instead
            - pkg: github.com/sirupsen/logrus
              desc: please use log/slog from the standard library instead
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
        - pattern: ^spew\.Dump$
        - pattern: ^println$
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
