linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - interfacer
    - megacheck
    - misspell
    - nlreturn
    - nolintlint
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wsl
