dist: bionic
language: go
os: linux
go:
  - '1.14'
install:
  - npm install -g snyk
  - make setup
jobs:
  include:
    - stage: check
      script:
        - make test-ci
        - bash <(curl -s https://codecov.io/bash)
    - stage: check
      script:
        - snyk monitor --org=czi
        - snyk test
    - stage: check
      script:
        - make lint
