[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.6.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.69"

[[constraint]]
  name = "github.com/honeycombio/libhoney-go"
  version = "1.8.1"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
