[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.10.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.36"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.6.1"

[[constraint]]
  name = "github.com/google/go-github"
  version = "25.0.4"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  version = "1.2.0"

[[constraint]]
  name = "github.com/honeycombio/libhoney-go"
  version = "1.10.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.5.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.29.0"

[prune]
  go-tests = true
  unused-packages = true
