name: Go

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: checkout
      uses: actions/checkout@v2

    - name: test
      run: make test-ci

    - name: configure aws creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.IDACCT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.IDACCT_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: ${{ secrets.TFE_AWS_ROLE }}
        role-duration-seconds: 900
