name: Upgrade AWS Mocks nightly

on:
  schedule:
  - cron: "10 20 * * 2"
  # So I can test manually
  workflow_dispatch: {}

jobs:
  upgrade-aws-mocks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.5
      id: go
    - run: make generate-mocks
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.CZIBUILDBOT_GITHUB_TOKEN }}
        branch: actionsbot/upgrade-aws-mocks
        commit-message: "Auto upgrade AWS Mocks"
        title: "[bot] Upgrade AWS Mocks"
        labels: "bot/merge"
