name: Upgrade AWS Mocks nightly

on:
  schedule:
    - cron: "10 20 * * *"
  workflow_dispatch: {}

jobs:
  upgrade-aws-mocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: aws/go.mod
        id: go
      - run: |
          make generate-mocks
          go mod tidy
        working-directory: aws
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CZIBUILDBOT_GITHUB_TOKEN }}
          branch: actionsbot/upgrade-aws-mocks
          commit-message: "Auto upgrade AWS Mocks"
          title: "[bot] Upgrade AWS Mocks"
          labels: "bot/merge"
