on: push

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - fix-mod
          - lint-ci
          - test-ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: Install dependencies
        run: make setup

      - name: make ${{ matrix.target }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
        run: make ${{ matrix.target }}
