on: push

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - check-mod
          - lint-ci
          - test-ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: Install dependencies
        run: make setup

      - name: make ${{ matrix.target }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
        run: make ${{ matrix.target }}
  build-and-push:
    runs-on: ubuntu-latest
    needs: run
    env:
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - run: make setup
      - run: env
      - run: curl -o $GITHUB_WORKSPACE/bin/docker-helper https://raw.githubusercontent.com/chanzuckerberg/infra-tools/3a244a92ad4e5bb3085f89043199c1abd3c3916b/docker-helper
      - run: chmod +x $GITHUB_WORKSPACE/bin/docker-helper
      - run: $GITHUB_WORKSPACE/bin/docker-helper build docker.pkg.github.com/chanzuckerberg/reaper/reaper .
      - run: $GITHUB_WORKSPACE/bin/docker-helper push docker.pkg.github.com/chanzuckerberg/reaper/reaper
