on: push

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - check-mod
          - lint-ci
          - test-ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: make setup

      - name: make ${{ matrix.target }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make ${{ matrix.target }}
