on:
  - pull_request

name: Update go.mod

jobs:
  update_go_mod:
    runs-on: [ARM64, self-hosted, Linux]
    outputs:
      updated_go_mod: ${{ steps.commit_go_mod.outputs.committed }}
    steps:
      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        with:
          app_id: ${{ secrets.CZI_GITHUB_HELPER_APP_ID }}
          private_key: ${{ secrets.CZI_GITHUB_HELPER_PK }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Update go.mod
        run: go mod tidy
      - uses: EndBug/add-and-commit@v9
        id: commit_go_mod
        with:
          add: -A
          message: ci - update go.mod
